// vue_tsc1/src/components/Header.vue
<script setup lang="ts">
const navArr = [
  { path: '/', name: 'Home' },
  { path: '/hello', name: 'HelloWorld' },
  { path: '/test', name: 'Test' }
];
</script>

<template>
  <header>
    <nav>
      <ul>
        <li v-for="item in navArr">
          <router-link :to="item.path"> {{ item.name }}</router-link>
        </li>
      </ul>
    </nav>
  </header>
</template>

<style scoped>
header {
  border-bottom: 1px solid #333;
}
nav {
  padding: 1rem 15px;
}
nav > ul {
  display: flex;
  gap: 1rem;
}
</style>

// clerk-react/src/pages/layouts/Header.tsx
import { Link } from 'react-router-dom';
import { SignedIn, SignedOut, SignInButton, UserButton } from '@clerk/clerk-react';

export default function Header() {
  return (
    <header>
      <nav>
        <ul style={{ display: 'flex', gap: '1rem' }}>
          <li>
            <Link to='/'>Home</Link>
          </li>
          <li>
            <Link to='/sub1'>Sub1</Link>
          </li>
          <li>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </li>
        </ul>
      </nav>
    </header>
  );
}
