// vue_tsc1/src/components/Header.vue
<script setup lang="ts">
const navArr = [
  { path: '/', name: 'Home' },
  { path: '/hello', name: 'HelloWorld' },
  { path: '/test', name: 'Test' }
];
</script>

<template>
  <header>
    <nav>
      <ul>
        <li v-for="item in navArr">
          <router-link :to="item.path"> {{ item.name }}</router-link>
        </li>
      </ul>
    </nav>
  </header>
</template>

<style scoped>
header {
  border-bottom: 1px solid #333;
}
nav {
  padding: 1rem 15px;
}
nav > ul {
  display: flex;
  gap: 1rem;
}
</style>

// zustand1/src/components/common/Header.tsx
import React from 'react';
import { Link, Outlet } from 'react-router-dom';
import styled from 'styled-components';

// style
const NavTag = styled.nav`
  background: #000;
  ul {
    display: flex;
    gap: 1.5rem;
    li a {
      display: block;
      color: #fff;
      font-size: 1.5rem;
      padding: 14px 0;
      margin-left: 2rem;
    }
  }
`;

const Header = () => {
  return (
    <div>
      <header>
        <NavTag>
          <ul>
            <li>
              <Link to="/">Logo</Link>
            </li>
            <li>
              <Link to="/">Home</Link>
            </li>
            <li>
              <Link to="/sub1">Sub1</Link>
            </li>
            <li>
              <Link to="/sub2">Sub2</Link>
            </li>
          </ul>
        </NavTag>
      </header>
      <Outlet />
    </div>
  );
};

export default Header;
